import React from 'react';
import { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ['200', '400', '600'] });

export const metadata: Metadata = {
  title: "Food Box",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="max-w-4xl mx-auto p-4">
          {/* AppProvider and Header components are used, but not imported */}
          {/* Import them from their respective files */}
          <AppProvider>
            <Header />

            {children}
            <footer className="border-t p-8 text-center text-gray-500 mt-8">
              &copy; 2024 All rights reserved
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
