import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from 'src/components/layout/Header'; 


const poppins = Poppins({ subsets: ["latin"], weight: ['200','400','600']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="max-w-4xl mx-auto p-4">
        <Header />
          {children}
          <footer className="border-t p-8 text-center text-gray-500 mt-8">
            &copy; 2024 All rights reserved
          </footer>
        </main>

      </body>
    </html>
  );
}
